# This workflow is for Eleventy projects using Node.js and deploying to GitHub Pages.
name: Deploy Eleventy to GitHub Pages

on:
  # Trigger the workflow on pushes to the 'main' branch
  push:
    branches:
      - main
  # Allow manual triggering of the workflow from the GitHub Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    # Use the latest Ubuntu runner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        # Action to check out your repository code
        uses: actions/checkout@v3

      - name: Set up Node.js
        # Action to set up Node.js environment. Adjust 'node-version' if needed.
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Use a stable Node.js version compatible with Eleventy

      - name: Install dependencies
        # Install Eleventy and any other project dependencies
        run: npm install

      - name: Build Eleventy site
        # Run the Eleventy build command.
        # This will generate the static files in the _site directory (default).
        run: npx @11ty/eleventy

      - name: Deploy to GitHub Pages
        # This action handles the deployment of the built site to the gh-pages branch.
        # It automatically sets up the git environment and pushes the content.
        uses: peaceiris/actions-gh-pages@v3
        with:
          # The personal access token (PAT) for authentication.
          # GITHUB_TOKEN is a special token provided by GitHub Actions for the current workflow.
          # It has permissions to push to gh-pages by default for this action.
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # The branch where the built site will be deployed.
          # This branch will then be served by GitHub Pages.
          publish_branch: gh-pages
          # The directory containing the static files generated by Eleventy.
          # Ensure this matches your Eleventy output directory.
          publish_dir: ./_site
          # Keep the commit history clean on the publish_branch.
          force_orphan: true
